#!/usr/bin/env bash
# Copyright (C) 2025 Patrick Brisbin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
set -euo pipefail

docker build --tag archlinux-downgrade/aur-publish-action:testing .
docker run -it --rm \
  --env "SSH_PRIVATE_KEY=$(<~/.ssh/aur)" \
  archlinux-downgrade/aur-publish-action:testing aur-publish downgrade \
  --version "11.5.1-rc-aur.1" \
  --git-email "$(git config get user.email)" \
  --git-username "$(git config get user.name)" \
  --no-publish
